/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import javax.swing.JOptionPane;

/**
 *
 * @author Eduar
 */
public class Ventana extends javax.swing.JInternalFrame {
int c=0, c2=0;
    /**
     * Creates new form NewJInternalFrame
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btn_Calcular = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btn_Cerrar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn_Suma = new javax.swing.JButton();
        btn_Resta = new javax.swing.JButton();
        btn_Mult = new javax.swing.JButton();
        btn_Divi = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        optSuma = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        optResta = new javax.swing.JRadioButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_texto = new javax.swing.JTextPane();
        jPanel13 = new javax.swing.JPanel();
        optMulti = new javax.swing.JRadioButton();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_texto2 = new javax.swing.JTextPane();
        jPanel15 = new javax.swing.JPanel();
        optDivi = new javax.swing.JRadioButton();
        jPanel16 = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Operaciones Arimeticas");
        jLabel1.setPreferredSize(new java.awt.Dimension(125, 30));
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(442, 50));
        jPanel3.setLayout(new java.awt.GridLayout(1, 4));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        btn_Calcular.setText("Calcular");
        btn_Calcular.setEnabled(false);
        btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularActionPerformed(evt);
            }
        });
        jPanel7.add(btn_Calcular);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        btn_Cerrar.setText("Cerrar");
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });
        jPanel8.add(btn_Cerrar);

        jPanel3.add(jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel9);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        btn_Suma.setText("Suma");
        btn_Suma.setEnabled(false);
        btn_Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SumaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_Suma);

        btn_Resta.setText("Resta");
        btn_Resta.setEnabled(false);
        btn_Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RestaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_Resta);

        btn_Mult.setText("Multiplicacion");
        btn_Mult.setEnabled(false);
        btn_Mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MultActionPerformed(evt);
            }
        });
        jPanel4.add(btn_Mult);

        btn_Divi.setText("Divicion");
        btn_Divi.setEnabled(false);
        btn_Divi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DiviActionPerformed(evt);
            }
        });
        jPanel4.add(btn_Divi);

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 120));
        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        buttonGroup1.add(optSuma);
        optSuma.setText("suma");
        optSuma.setEnabled(false);
        optSuma.setPreferredSize(new java.awt.Dimension(75, 22));
        optSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSumaActionPerformed(evt);
            }
        });
        jPanel1.add(optSuma);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridLayout(1, 0));

        buttonGroup1.add(optResta);
        optResta.setText("Resta");
        optResta.setEnabled(false);
        optResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optRestaActionPerformed(evt);
            }
        });
        jPanel11.add(optResta);

        jPanel1.add(jPanel11);

        jPanel12.setLayout(new java.awt.GridLayout(1, 0));

        txt_texto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_textoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txt_texto);

        jPanel12.add(jScrollPane1);

        jPanel1.add(jPanel12);

        jPanel13.setLayout(new java.awt.GridLayout(1, 0));

        buttonGroup1.add(optMulti);
        optMulti.setText("Multiplicacion");
        optMulti.setEnabled(false);
        jPanel13.add(optMulti);

        jPanel1.add(jPanel13);

        jPanel14.setLayout(new java.awt.GridLayout(1, 0));

        txt_texto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_texto2KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txt_texto2);

        jPanel14.add(jScrollPane2);

        jPanel1.add(jPanel14);

        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        buttonGroup1.add(optDivi);
        optDivi.setText("divicion");
        optDivi.setEnabled(false);
        optDivi.setPreferredSize(new java.awt.Dimension(20, 20));
        optDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optDiviActionPerformed(evt);
            }
        });
        jPanel15.add(optDivi);

        jPanel1.add(jPanel15);

        jPanel16.setLayout(new java.awt.GridLayout(1, 0));

        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("0.0");
        jPanel16.add(lblResultado);

        jPanel1.add(jPanel16);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optSumaActionPerformed

    private void optDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optDiviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optDiviActionPerformed

    private void optRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optRestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optRestaActionPerformed

    private void btn_RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RestaActionPerformed
        // TODO add your handling code here:
         String n1,n2;
        n1=txt_texto.getText();
        n2=txt_texto2.getText();
        Validaciones v=new Validaciones();
        if(v.ValidarEnteros(n1).equals("decimal")){
            //JOptionPane.showMessageDialog(null, "hola");
            float a = Float.parseFloat(n1);
            if (v.ValidarEnteros(n2).equals("decimal")){
                float b = Float.parseFloat(n2);
                float r = a - b;
                this.lblResultado.setText(Float.toString(r));
            }
        }else if (v.ValidarEnteros(n1).equals("entero")){
            int a = Integer.parseInt(n1);
            if(v.ValidarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                int r = a-b;
                this.lblResultado.setText(Integer.toString(r));
            }else if(v.ValidarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                int r = a-b;
                this.lblResultado.setText(Integer.toString(r));
                }
        }
        
    }//GEN-LAST:event_btn_RestaActionPerformed

    private void btn_DiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DiviActionPerformed
        // TODO add your handling code here:
                String n1,n2;
        n1=txt_texto.getText();
        n2=txt_texto2.getText();
        Validaciones v=new Validaciones();
        if(v.ValidarEnteros(n1).equals("decimal")){
            //JOptionPane.showMessageDialog(null, "hola");
            float a = Float.parseFloat(n1);
            if (v.ValidarEnteros(n2).equals("decimal")){
                float b = Float.parseFloat(n2);
                float r = a / b;
                this.lblResultado.setText(Float.toString(r));
            }
        }else if (v.ValidarEnteros(n1).equals("entero")){
            float a = Float.parseFloat(n1);
            if(v.ValidarEnteros(n2).equals("entero")){
                float b = Integer.parseInt(n2);
                float r = a/b;
                this.lblResultado.setText(Float.toString(r));
            }else if(v.ValidarEnteros(n2).equals("decimal")){
                float b = Float.parseFloat(n2);
                float r = a/b;
                this.lblResultado.setText(Float.toString(r));
                }
        } 
        
    }//GEN-LAST:event_btn_DiviActionPerformed

    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
        // TODO add your handling code here:
         this.hide();
    }//GEN-LAST:event_btn_CerrarActionPerformed

    private void txt_textoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_textoKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();//convertir un char a ascii
        if (key==8){
            c--;
        }if(c<0){
            c=0;
        }
        if ((key>=48 && key<=57) || key == 46 ){
            c++;
        }
        else{
            evt.consume();
        }
        if(c>0 && c2>0){
            btn_Suma.setEnabled(true);
            btn_Resta.setEnabled(true);
            btn_Mult.setEnabled(true);
            btn_Divi.setEnabled(true);
            optSuma.setEnabled(true);
            optResta.setEnabled(true);
            optMulti.setEnabled(true);
            optDivi.setEnabled(true);
            btn_Calcular.setEnabled(true);
        }
        else{
            btn_Suma.setEnabled(false);
            btn_Resta.setEnabled(false);
            btn_Mult.setEnabled(false);
            btn_Divi.setEnabled(false);
            optSuma.setEnabled(false);
            optResta.setEnabled(false);
            optMulti.setEnabled(false);
            optDivi.setEnabled(false);
            btn_Calcular.setEnabled(false);
        }
    }//GEN-LAST:event_txt_textoKeyTyped

    private void txt_texto2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_texto2KeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();//convertir un char a ascii
        if (key==8){
            c2--;
        }
        if(c2<0){
            c2=0;
        }
        if ((key>=48 && key<=57) || key == 46){
            c2++;
        }
        else{
            evt.consume();
        }
        if(c2>0 && c>0){
            btn_Suma.setEnabled(true);
            btn_Resta.setEnabled(true);
            btn_Mult.setEnabled(true);
            btn_Divi.setEnabled(true);
            optSuma.setEnabled(true);
            optResta.setEnabled(true);
            optMulti.setEnabled(true);
            optDivi.setEnabled(true);
            btn_Calcular.setEnabled(true);
        }
        else{
            btn_Suma.setEnabled(false);
            btn_Resta.setEnabled(false);
            btn_Mult.setEnabled(false);
            btn_Divi.setEnabled(false);
            optSuma.setEnabled(false);
            optResta.setEnabled(false);
            optMulti.setEnabled(false);
            optDivi.setEnabled(false);
            btn_Calcular.setEnabled(false);
    }//GEN-LAST:event_txt_texto2KeyTyped
    }
    private void btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularActionPerformed
        // TODO add your handling code here:
        String n1 = txt_texto.getText();
        String n2 = txt_texto.getText();
        if (optSuma.isSelected()){
            int a = Integer.parseInt(n1);
            int b = Integer.parseInt(n2);
            int c = a+b;
            this.lblResultado.setText(Integer.toString(c));
        }else if (optSuma.isSelected()){
            float a = Float.parseFloat(n1);
            float b = Float.parseFloat(n2);
            float c = a+b;
            this.lblResultado.setText(Float.toString(c));
        }else if (optResta.isSelected()){
            int a = Integer.parseInt(n1);
            int b = Integer.parseInt(n2);
            int c = a-b;
            this.lblResultado.setText(Integer.toString(c));
        }else if (optResta.isSelected()){
            float a = Float.parseFloat(n1);
            float b = Float.parseFloat(n2);
            float c = a-b;
            this.lblResultado.setText(Float.toString(c));
        }else if (optDivi.isSelected()){
            float a = Float.parseFloat(n1);
            float b = Float.parseFloat(n2);
            float c = a/b;
            this.lblResultado.setText(Float.toString(c));
        }else if (optDivi.isSelected()){
            float a = Float.parseFloat(n1);
            float b = Float.parseFloat(n2);
            float c = a/b;
            this.lblResultado.setText(Float.toString(c));
        }else if (optMulti.isSelected()){
            int a = Integer.parseInt(n1);
            int b = Integer.parseInt(n2);
            int c = a*b;
            this.lblResultado.setText(Integer.toString(c));
        }else if (optMulti.isSelected()){
            float a = Float.parseFloat(n1);
            float b = Float.parseFloat(n2);
            float c = a*b;
            this.lblResultado.setText(Float.toString(c));
        }
    }//GEN-LAST:event_btn_CalcularActionPerformed

    private void btn_SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SumaActionPerformed
        // TODO add your handling code here:
        String n1,n2;
        n1=txt_texto.getText();
        n2=txt_texto2.getText();
        Validaciones v=new Validaciones();
        if(v.ValidarEnteros(n1).equals("decimal")){
            //JOptionPane.showMessageDialog(null, "hola");
            float a = Float.parseFloat(n1);
            if (v.ValidarEnteros(n2).equals("decimal")){
                float b = Float.parseFloat(n2);
                float r = a + b;
                this.lblResultado.setText(Float.toString(r));
            }
        }else if (v.ValidarEnteros(n1).equals("entero")){
            int a = Integer.parseInt(n1);
            if(v.ValidarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                int r = a+b;
                this.lblResultado.setText(Integer.toString(r));
            }else if(v.ValidarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                int r = a+b;
                this.lblResultado.setText(Integer.toString(r));
                }
        } 
        
    }//GEN-LAST:event_btn_SumaActionPerformed

    private void btn_MultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MultActionPerformed
        // TODO add your handling code here:
                String n1,n2;
        n1=txt_texto.getText();
        n2=txt_texto2.getText();
        Validaciones v=new Validaciones();
        if(v.ValidarEnteros(n1).equals("decimal")){
            //JOptionPane.showMessageDialog(null, "hola");
            float a = Float.parseFloat(n1);
            if (v.ValidarEnteros(n2).equals("decimal")){
                float b = Float.parseFloat(n2);
                float r = a * b;
                this.lblResultado.setText(Float.toString(r));
            }
        }else if (v.ValidarEnteros(n1).equals("entero")){
            int a = Integer.parseInt(n1);
            if(v.ValidarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                int r = a*b;
                this.lblResultado.setText(Integer.toString(r));
            }else if(v.ValidarEnteros(n2).equals("entero")){
                int b = Integer.parseInt(n2);
                int r = a*b;
                this.lblResultado.setText(Integer.toString(r));
                }
        } 
        
    }//GEN-LAST:event_btn_MultActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Calcular;
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JButton btn_Divi;
    private javax.swing.JButton btn_Mult;
    private javax.swing.JButton btn_Resta;
    private javax.swing.JButton btn_Suma;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton optDivi;
    private javax.swing.JRadioButton optMulti;
    private javax.swing.JRadioButton optResta;
    private javax.swing.JRadioButton optSuma;
    private javax.swing.JTextPane txt_texto;
    private javax.swing.JTextPane txt_texto2;
    // End of variables declaration//GEN-END:variables
}
